import requests

cookies = {'pc': 'nj', 'session_tracker': 'zjHG7eAhSa7mjYwKZE.0.1569096420706.Z0FBQUFBQmRob0xreFE1MVVJOERKTk1Sei1tZ3BwcTZobmlLaURkeEs3dFFycnJRZWxpQU9teUd4d1U1QUFONGFzU04yb2JpZnAwUmhkQXhNWVg0M2xCM2VNbTlNVGxURDVwRGF1bFVYQ2RCTlZQVmdzR2Z4U0hocElKRmV2eE4wbEZoamJReU5QSUQ', 'initref': 'reddithelp.com', 'recent_srs': 't5_2qh4a%2Ct5_2s1s3%2Ct5_htquw%2Ct5_m2yqp%2Ct5_vdb9k%2Ct5_3gyaj%2Ct5_258pmk%2Ct5_m479s%2Ct5_1zu21w%2Ct5_7h23l',
           'token': 'eyJhY2Nlc3NUb2tlbiI6IjQwNjQ2ODc5LUpHeGJNaDlrQUxKNW1pRkw2X2s5LUtuLURTMCIsInRva2VuVHlwZSI6ImJlYXJlciIsImV4cGlyZXMiOiIyMDE5LTA5LTIxVDIwOjM5OjQ0LjY2NVoiLCJyZWZyZXNoVG9rZW4iOiI0MDY0Njg3OS0tNC1GeExVckhEOW1OMnJQWDAzbTktUEhHWnMiLCJzY29wZSI6IiogZW1haWwiLCJ1bnNhZmVMb2dnZWRPdXQiOmZhbHNlfQ==.2', 'reddaid': 'VTY4J3G5XPJ6L6IB',
           'loid': '0000000000000o77bz.2.1434669370561.Z0FBQUFBQmRkcGU3SHAwYWdOMFR0TjFQak1jQ0VKeHVta2o5eVI3TkN6cjIwbURuVEMwMG1IeUc5NXZ4eThMbThFWHI5dFFKY2l4TXpFc1ZlTl9MYW5rdFRPVmZkZmZlWlA1Q1FzVG9KQlYxeDNkZm1vZTBRVkFUa0tmbm9MUE1vbzFJVlkxdEhrXzc', 'redesign_optout': 'true', 'rabt': '', 'rseor3': '', 'reddit_session': '40646879%2C2019-08-26T23%3A33%3A24%2C399db4bcaeb779da734b97b1476b45bef8bf8b7e',
           'USER': 'eyJwcmVmcyI6eyJnbG9iYWxUaGVtZSI6IlJFRERJVCIsImZlYXR1cmVzVmlld2VkSGlzdG9yeSI6eyJjb21tZW50Rm9ybSI6eyJtYXJrZG93bk1vZGVOb3RpZmljYXRpb24iOnRydWV9fSwiY29sbGFwc2VkVHJheVNlY3Rpb25zIjp7ImZhdm9yaXRlcyI6ZmFsc2UsIm11bHRpcyI6ZmFsc2UsIm1vZGVyYXRpbmciOmZhbHNlLCJzdWJzY3JpcHRpb25zIjpmYWxzZSwicHJvZmlsZXMiOmZhbHNlfSwibmlnaHRtb2RlIjpmYWxzZSwic3Vic2NyaXB0aW9uc1Bpbm5lZCI6ZmFsc2V9LCJsYW5ndWFnZSI6ImVuIn0=', 'compact': 'true', 'theme': 'daymode',
           '__utma': '55650728.383002901.1535767018.1546147696.1546289010.45', '_ga': 'GA1.2.383002901.1535767018', 'cto_lwid': 'a5bef70f-c239-4fe1-ba8e-91bd04db9b87', '__stripe_mid': 'b4ff71ff-5ee5-4132-b2da-4f870f1e1e37', '__gads': 'ID=25152abc0d728197:T=1537220095:S=ALNI_Mb8_CNipHx0gLhbJhNHdtgEEKnt5w', 'edgebucket': 'TMftesATgIPYM3cVwC', }

headers = {'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'Host': 'www.reddit.com', 'Accept-Language': 'en-us', 'Accept-Encoding': 'br, gzip, deflate', 'Origin': 'https://www.reddit.com', 'Referer': 'https://www.reddit.com/', 'Connection': 'keep-alive', 'Content-Length': '116', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15',
           'X-Requested-With': 'XMLHttpRequest', }

data = {'id': '', 'executed': 'deleted', 'client_id': 'ZOd1K69as5oYrQ', 'uh': 'trk0q5i5nv33d1a308b2674674d8b56301258161fdd5130aa2', 'renderstyle': 'html'}

response = requests.post('https://www.reddit.com/api/deleteapp', headers=headers, cookies=cookies, data=data)


'''&lt;li id="developed-app-LJ06U33Q50tC8g" class="developed-app rounded "&gt;&lt;div class="app-icon"&gt;&amp;nbsp;&lt;img src="//www.redditstatic.com/defaultapp.png"&gt;&amp;nbsp;&lt;/div&gt;&lt;a class="edit-app-button collapsed" href="javascript:void(0)"&gt;edit&lt;/a&gt;&lt;div class="app-details"&gt;&lt;h2&gt;FlairBot&lt;/h2&gt;&lt;h3&gt;web app&lt;/h3&gt;&lt;h3&gt;LJ06U33Q50tC8g&lt;/h3&gt;&lt;/div&gt;&lt;div class="app-description"&gt;Bot for assisting moderators with moderation using 
post flairs.&lt;/div&gt;&lt;div class="edit-app "&gt;&lt;a class="edit-app-icon-button" href="javascript:void(0)"&gt;change icon&lt;/a&gt;&lt;form method="post" enctype="multipart/form-data" target="app-icon-upload-LJ06U33Q50tC8g-iframe" id="app-icon-upload-LJ06U33Q50tC8g" class="ajax-upload-form pretty-form" action="/api/setappicon" onsubmit="return post_multipart_form(this, '/api/setappicon')"&gt;&lt;input type="hidden" name="id" value="#app-icon-upload-LJ06U33Q50tC8g" /&gt;&lt;input 
type="hidden" name="uh" value="m8mb9p0qrk813502e165c7b6c55b1745ff77f71de15c3a2d80" /&gt;&lt;input type="file" name="file" /&gt;&lt;button type="submit"&gt;upload&lt;/button&gt;&lt;span class="error IMAGE_ERROR field-" style="display:none"&gt;&lt;/span&gt;&lt;input type="hidden" name="client_id" value="LJ06U33Q50tC8g" /&gt;&lt;span class="error TOO_LONG field-file" style="display:none"&gt;&lt;/span&gt;&lt;span class="error BAD_IMAGE field-file" style="display:none"&gt;&lt;/span&gt;&lt;span 
class="status"&gt;&lt;/span&gt;&lt;script type="text/javascript"&gt;function completedUploadImage (status, img_src, name, errors, form_id) { /* should only be called when the uploaded file is too large */ form_id = $.with_default(form_id, "app-icon-upload-LJ06U33Q50tC8g"); if (status == "failed") { $("#app-icon-upload-LJ06U33Q50tC8g").find(".status").html(""); for (var i in errors) { $("#app-icon-upload-LJ06U33Q50tC8g").find(".error." + errors[i][0]) .show().text(errors[i][1]); } } 
}&lt;/script&gt;&lt;iframe src="about:blank" name="app-icon-upload-LJ06U33Q50tC8g-iframe" id="app-icon-upload-LJ06U33Q50tC8g-iframe"&gt;&lt;/iframe&gt;&lt;/form&gt;&lt;div class="edit-app-form"&gt;&lt;form method="post" action="/api/updateapp" class="pretty-form" id="update-app-LJ06U33Q50tC8g" onsubmit="return post_form(this, 'updateapp', function(x) {return 'updating...'})"&gt;&lt;input type="hidden" name="uh" value="m8mb9p0qrk813502e165c7b6c55b1745ff77f71de15c3a2d80" /&gt;&lt;input 
type="hidden" name="client_id" value="LJ06U33Q50tC8g" /&gt;&lt;input type="hidden" name="app_type" value="web" /&gt;&lt;table class="preftable"&gt;&lt;tr&gt;&lt;th&gt;secret&lt;/th&gt;&lt;td class="prefright"&gt;O6pQD6kOJTTREX7dT38R4IWH-8s&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;th&gt;name&lt;/th&gt;&lt;td class="prefright"&gt;&lt;input class="text" name="name" value="FlairBot"&gt;&lt;span class="error NO_TEXT field-name" 
style="display:none"&gt;&lt;/span&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;th&gt;description&lt;/th&gt;&lt;td class="prefright"&gt;&lt;textarea name="description"&gt;Bot for assisting moderators with moderation using post flairs.&lt;/textarea&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;th&gt;about url&lt;/th&gt;&lt;td class="prefright"&gt;&lt;input class="text" name="about_url" value=""&gt;&lt;span class="error BAD_URL field-about_url" 
style="display:none"&gt;&lt;/span&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;th&gt;redirect uri&lt;/th&gt;&lt;td class="prefright"&gt;&lt;input class="text" name="redirect_uri" value="https://oauth.lilspazjoekp.com/reddit_oauth"&gt;&lt;span class="error NO_URL field-redirect_uri" style="display:none"&gt;&lt;/span&gt;&lt;span class="error BAD_URL field-redirect_uri" style="display:none"&gt;&lt;/span&gt;&lt;span class="error INVALID_SCHEME field-redirect_uri" 
style="display:none"&gt;&lt;/span&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;button type="submit"&gt;update app&lt;/button&gt;&lt;span class="status"&gt;&lt;/span&gt;&lt;/form&gt;&lt;/div&gt;&lt;div class="edit-app-form pretty-form"&gt;&lt;table class="preftable"&gt;&lt;tr&gt;&lt;th&gt;developers&lt;/th&gt;&lt;td class="prefright"&gt;&lt;ul&gt;&lt;li id="app-dev-LJ06U33Q50tC8g-57009903970"&gt;UninsurableApogee&amp;#32;&lt;span class="gray"&gt;(that's you!)&lt;/span&gt;&amp;#32;&lt;form 
method="post" action="/api/removedeveloper" class="toggle ajax-yn-button removedeveloper-button "&gt;&lt;input type="hidden" name="_op" value="removedeveloper" /&gt;&lt;input type="hidden" name="name" value="UninsurableApogee" /&gt;&lt;input type="hidden" name="client_id" value="LJ06U33Q50tC8g" /&gt;&lt;span class="option main active"&gt;&lt;a href="javascript:void(0)" class="togglebutton"&gt;remove&lt;/a&gt;&lt;/span&gt;&lt;span class="option error"&gt;are you sure? &amp;#32;&lt;a 
href="javascript:void(0)" class="yes"&gt;yes&lt;/a&gt;&amp;#32;/&amp;#32;&lt;a href="javascript:void(0)" class="no"&gt;no&lt;/a&gt;&lt;/span&gt;&lt;/form&gt;&lt;/li&gt;&lt;/ul&gt;&lt;br&gt;&lt;form method="post" action="/api/adddeveloper" class="pretty-form" id="app-developer-LJ06U33Q50tC8g" onsubmit="return post_form(this, 'adddeveloper', function(x) {return 'adding...'})"&gt;&lt;input type="hidden" name="uh" value="m8mb9p0qrk813502e165c7b6c55b1745ff77f71de15c3a2d80" /&gt;&lt;input 
type="hidden" name="client_id" value="LJ06U33Q50tC8g" /&gt;add developer:&lt;input class="text" name="name"&gt;&lt;br&gt;&lt;span class="error TOO_MANY_DEVELOPERS field-" style="display:none"&gt;&lt;/span&gt;&lt;span class="error OAUTH2_INVALID_CLIENT field-client_id" style="display:none"&gt;&lt;/span&gt;&lt;span class="error DEVELOPER_ALREADY_ADDED field-name" style="display:none"&gt;&lt;/span&gt;&lt;span class="error USER_DOESNT_EXIST field-name" 
style="display:none"&gt;&lt;/span&gt;&lt;span class="error NO_USER field-name" style="display:none"&gt;&lt;/span&gt;&lt;span class="error DEVELOPER_FIRST_PARTY_APP field-name" style="display:none"&gt;&lt;/span&gt;&lt;span class="error DEVELOPER_PRIVILEGED_ACCOUNT field-name" style="display:none"&gt;&lt;/span&gt;&lt;span class="status"&gt;&lt;/span&gt;&lt;/form&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;&lt;div class="delete-app-button"&gt;&lt;form class="toggle deleteapp-button " 
action="#" method="get"&gt;&lt;input type="hidden" name="executed" value="deleted"/&gt;&lt;input type="hidden" name="client_id" value="LJ06U33Q50tC8g"/&gt;&lt;span class="option main active"&gt;&lt;a href="#" class="togglebutton access-required" onclick="return toggle(this)" &gt;delete app&lt;/a&gt;&lt;/span&gt;&lt;span class="option error"&gt;are you sure? &amp;#32;&lt;a href="javascript:void(0)" class="yes" onclick='change_state(this, "deleteapp", r.apps.deleted, undefined, 
null)'&gt;yes&lt;/a&gt;&amp;#32;/&amp;#32;&lt;a href="javascript:void(0)" class="no" onclick="return toggle(this)"&gt;no&lt;/a&gt;&lt;/span&gt;&lt;/form&gt;&lt;/div&gt;&lt;/div&gt;&lt;/li&gt;'''.replace('&lt;', '<').replace('&gt;', '>



